### ISSUE TITLE
Get working on esp8266 arduino platform.

### ISSUE THREAD

**Issue by CptanPanic** [allthingstalk/arduino-client#3]
I haven't tested this yet, as I do not have a esp8266 at the moment, but was wondering if you thought this should work on this chip now that it can be programmed via the arduino IDE?  If not this would be great addition as this is a great low-cost IoT platform.  If it already does, then you should at least update the Readme.  
Thanks.

**Comment by ATT-JBO** [comment]
HI,
We have not yet been able to test this little board ourselves.  The att-library supports all communication devices that come with a communiction library based on the Client.h interface. Something like this: https://github.com/Diaoul/arduino-ESP8266/blob/master/ESP8266Client.h which looks promising, but as already mentioned, it's not yet tested.

**Comment by ATT-JBO** [comment]
FYI: we now have a demo sketch included in the library for the esp8266
